# Generated by Django 5.1.1 on 2024-10-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementApp', '0005_alter_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
